package justgo

var ConfigKey configKey

type configKey struct {
	APP_NAME,
	APP_PORT,
	LOG_LEVEL,

	NEWRELIC_ENABLED,
	NEWRELIC_LICENSE,

	STATSD_ENABLED,
	STATSD_HOST,
	STATSD_PORT,
	STATSD_PREFIX,

	STATSD_FLUSH_PERIOD_IN_SECONDS,

	SENTRY_ENABLED,
	SENTRY_DSN,

	DEFAULT_INTERFACE_HTTP_ENABLED,

	DB_DRIVER,
	DB_CONNECTION_STRING,
	DB_CONNECTION_POOL string
}

func init() {
	ConfigKey = configKey{
		APP_NAME:  "APP_NAME",
		LOG_LEVEL: "LOG_LEVEL",
		APP_PORT:  "APP_PORT",

		NEWRELIC_ENABLED: "NEWRELIC_ENABLED",
		NEWRELIC_LICENSE: "NEWRELIC_LICENSE",

		STATSD_HOST:                    "STATSD_HOST",
		STATSD_PORT:                    "STATSD_PORT",
		STATSD_PREFIX:                  "STATSD_PREFIX",
		STATSD_FLUSH_PERIOD_IN_SECONDS: "STATSD_FLUSH_PERIOD_IN_SECONDS",
		STATSD_ENABLED:                 "STATSD_ENABLED",

		SENTRY_ENABLED: "SENTRY_ENABLED",
		SENTRY_DSN:     "SENTRY_DSN",

		DEFAULT_INTERFACE_HTTP_ENABLED: "DEFAULT_INTERFACE_HTTP_ENABLED",

		DB_DRIVER:            "DB_DRIVER",
		DB_CONNECTION_STRING: "DB_CONNECTION_STRING",
		DB_CONNECTION_POOL:   "DB_CONNECTION_POOL",
	}
}
